### PR TITLE
Hotfix production issues

### PR DESCRIPTION
**Pull request by agroblervf**
Hot fix for an issue where tickets were not generated during certain incoming calls.
It was due to the new feature for reload and multi tab support. With multiple tabs we need to select one that will be processing the call, as to not create duplicate tickets. The implementation was to pick the one that's in focus when the call comes in, which was wrong in hindsight as agents may be on another tab/window at the time the call comes in.
Now the tab that first gets the event is designated as the processing tab. If the instance sees that another tab is already processing the call it will not continue itself.

### CODE REVIEW

**Comment by shubhdevf** [comment]
This issue is affecting us. We hope the fix is released today.

**Comment by agroblervf** [comment]
> This issue is affecting us. We hope the fix is released today.

@shubhdevf this has already been deployed to marketplace as version 2.2.1.
If an agent is still experiencing an issue please ask them to clear their browser cache (cookies and other site data).

**Comment by AlexD1979** [comment]
i am not sure if this will fix my issue .. I have multiple tabs opened in Zendesk and for each tab Zendesk CTI adapter opens a new tab for Connect login process,.. proceed with login and then close the tab again. I have now on multiple tabs inside Zendesk multiple Softphones. Will this fix also avoid this ?

**Comment by agroblervf** [comment]
> i am not sure if this will fix my issue .. I have multiple tabs opened in Zendesk and for each tab Zendesk CTI adapter opens a new tab for Connect login process,.. proceed with login and then close the tab again. I have now on multiple tabs inside Zendesk multiple Softphones. Will this fix also avoid this ?

@AlexD1979 Each tab has its own softphone. However the Connect login process should only happen once. Unless you're using incognito mode or not allowing cookies.
Multiple softphones are all connected to the same server Connect session. Only one tab is selected as a "processing" tab though. Meaning you can accept and end the call in any of the tabs and only one ticket will be created/updated.

**Review by dineshsundar007 — APPROVED** [review]

**Pull request merged**
